name: scrape-precios

on:
  schedule:
    # Ejecutar a cada hora de 08:00 a 17:00 Bogotá, lunes a sábado. (UTC 13-22 Mon–Sat)
    - cron: "0 13-22 * * 1-6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread oauth2client pandas
          python -m playwright install --with-deps chromium
      - name: Ejecutar scraper
        env:
          SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          TIME_ZONE: America/Bogota
          BATCH_SIZE: '220'
        run: |
          python exito_scraper.py
